name:  First workflows

on:
  push:
    branches:
      - main

jobs:
  exemples-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome message
        run: echo "welcome to github"
      - name: Checkout ripository
        uses: actions/checkout@v4.4.0
      
      - name: chekout files
        run: ls -la

   
   
