name: push request workflow
on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
      - "package.json"
      - "test.sh"
  pull_request:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
      - "package.json"
      - "test.sh"
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.4.0
      - name: Run tests
        run: npm test
        

   